const products = [
 {id:'falcon-x8',name:'Falcon X8 Executive',category:'Aircraft',kind:'aircraft',price:2850000,priceLabel:'$2,850,000',specs:['8 seats','4,200 km range','2025'],tag:'New arrival',image:'https://images.unsplash.com/photo-1474302770737-173ee21bab63?auto=format&fit=crop&w=1200&q=85',description:'A refined long-range business aircraft combining a quiet cabin, advanced avionics and the range to connect major cities without compromise.'},
 {id:'skyline-jet',name:'Skyline S4 Jet',category:'Aircraft',kind:'aircraft',price:4190000,priceLabel:'$4,190,000',specs:['10 seats','5,800 km range','2024'],tag:'Long range',image:'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=1200&q=85',description:'A sleek, efficient private jet made for comfortable intercontinental journeys and exceptional operational flexibility.'},
 {id:'aircraft-turboprop',name:'AeroTwin 620',category:'Aircraft',kind:'aircraft',price:1320000,priceLabel:'$1,320,000',specs:['6 seats','2,100 km range','2025'],tag:'Versatile',image:'https://images.unsplash.com/photo-1559628233-100c798642d4?auto=format&fit=crop&w=1200&q=85',description:'Dependable twin-engine performance and a spacious cabin for regional routes, private travel and business operations.'},
 {id:'meridian-s',name:'Meridian S-Class',category:'Cars',kind:'cars',price:118500,priceLabel:'$118,500',specs:['4 doors','Electric','2025'],tag:'Electric',image:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=85',description:'A quiet, all-electric grand tourer with elegant lines, intuitive technology and a range designed for everyday freedom.'},
 {id:'evoque-gt',name:'Evoque GT Coupe',category:'Cars',kind:'cars',price:164900,priceLabel:'$164,900',specs:['2 doors','520 hp','2025'],tag:'Performance',image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85',description:'A sculpted performance coupe with confident handling, a handcrafted interior and exhilarating twin-turbo power.'},
 {id:'terra-x',name:'Terra X Adventure',category:'Cars',kind:'cars',price:87900,priceLabel:'$87,900',specs:['5 seats','AWD','2025'],tag:'All terrain',image:'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=85',description:'Ready for weekday commutes and faraway trails, with intelligent all-wheel drive and generous cargo space.'},
 {id:'vortex-r',name:'Vortex R 1000',category:'Motorcycles',kind:'motorcycles',price:26900,priceLabel:'$26,900',specs:['998 cc','205 hp','2025'],tag:'Superbike',image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85',description:'Track-bred precision meets road-ready control in this lightweight superbike, engineered for confident high-speed riding.'},
 {id:'strada-v4',name:'Strada V4 Sport',category:'Motorcycles',kind:'motorcycles',price:22400,priceLabel:'$22,400',specs:['1,103 cc','180 hp','2025'],tag:'Sport touring',image:'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=85',description:'An agile sport motorcycle with long-distance comfort, premium components and responsive V4 performance.'},
 {id:'nighthawk-rr',name:'Nighthawk RR',category:'Motorcycles',kind:'motorcycles',price:31800,priceLabel:'$31,800',specs:['999 cc','215 hp','2025'],tag:'Limited edition',image:'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=85',description:'A limited-run superbike with a carbon-inspired finish, race-derived electronics and razor-sharp cornering response.'}
];
const nav = `<header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.html"><span class="brand-mark">GL</span><span>GLOBE LINK<small>MOVE WITHOUT LIMITS</small></span></a><nav class="nav-links" id="navLinks"><a href="index.html">Home</a><a href="vehicles.html">Vehicles</a><a href="aircraft.html">Aircraft</a><a href="cars.html">Cars</a><a href="motorcycles.html">Motorcycles</a><a href="shipping.html">Shipping</a><a href="track.html">Track order</a></nav><div class="nav-actions"><a class="cart-link" href="checkout.html" aria-label="Shopping cart">🛒<span class="cart-count" id="cartCount">0</span></a><a class="btn btn-sm" href="vehicles.html">Explore stock ↗</a><button class="menu-toggle" id="menuToggle" aria-label="Open menu">☰</button></div></div></header>`;
const footer = `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="index.html" style="color:white"><span class="brand-mark">GL</span><span>GLOBE LINK<small style="color:#b7cbd2">MOVE WITHOUT LIMITS</small></span></a><p>Transportation made easy at affordable prices. Your next journey starts here.</p></div><div><h4>Explore</h4><div class="footer-nav"><a href="vehicles.html">All vehicles</a><a href="aircraft.html">Aircraft</a><a href="cars.html">Cars</a><a href="motorcycles.html">Motorcycles</a></div></div><div><h4>Customer care</h4><div class="footer-nav"><a href="shipping.html">Shipping & rates</a><a href="track.html">Track a shipment</a><a href="faq.html">FAQs</a><a href="contact.html">Contact us</a></div></div><div><h4>Company</h4><div class="footer-nav"><a href="about.html">About Globe Link</a><a href="contact.html">Get in touch</a><a href="checkout.html">Your cart</a></div></div></div><div class="footer-bottom"><span>© 2025 Globe Link Mobility. All rights reserved.</span><span>Built for journeys that matter.</span></div></div></footer>`;
document.addEventListener('DOMContentLoaded',()=>{
 const header=document.getElementById('siteHeader');if(header)header.innerHTML=nav;const foot=document.getElementById('siteFooter');if(foot)foot.innerHTML=footer;
 const cart=()=>JSON.parse(localStorage.getItem('gl-cart')||'[]');const saveCart=x=>{localStorage.setItem('gl-cart',JSON.stringify(x));updateCart()};function updateCart(){const count=document.getElementById('cartCount');if(count)count.textContent=cart().reduce((n,x)=>n+x.qty,0)}updateCart();
 document.getElementById('menuToggle')?.addEventListener('click',()=>document.getElementById('navLinks')?.classList.toggle('open'));
 const card=(p)=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="badge">${p.tag}</span></div><div class="product-info"><span class="type">${p.category}</span><h3>${p.name}</h3><div class="specs">${p.specs.map(s=>`<span>${s}</span>`).join('')}</div><div class="price-row"><span class="price">${p.priceLabel} <small>USD</small></span><a class="btn btn-sm" href="vehicle.html?id=${p.id}">View details</a></div></div></article>`;
 const list=document.querySelector('[data-products]');if(list){const type=list.dataset.products;const filtered=products.filter(p=>type==='all'||p.kind===type);list.innerHTML=filtered.map(card).join('');const search=document.getElementById('vehicleSearch'),sort=document.getElementById('vehicleSort');const apply=()=>{let found=filtered.filter(p=>p.name.toLowerCase().includes((search?.value||'').toLowerCase()));if(sort?.value==='low')found.sort((a,b)=>a.price-b.price);if(sort?.value==='high')found.sort((a,b)=>b.price-a.price);list.innerHTML=found.length?found.map(card).join(''):'<div class="empty-state">No vehicles match your search. Try another keyword.</div>'};search?.addEventListener('input',apply);sort?.addEventListener('change',apply)}
 const detail=document.getElementById('vehicleDetail');if(detail){const id=new URLSearchParams(location.search).get('id')||products[0].id;const p=products.find(x=>x.id===id)||products[0];detail.innerHTML=`<div><img class="detail-image" src="${p.image}" alt="${p.name}"><div class="section" style="padding:28px 0"><h2>Designed for the way you move</h2><p class="muted">${p.description} Every Globe Link vehicle is inspected by our specialists and delivered with transparent documentation and dedicated support.</p></div></div><div class="detail-panel"><span class="eyebrow">${p.category} · ${p.tag}</span><h1>${p.name}</h1><p class="muted">Premium condition · Globe Link verified</p><div class="detail-price">${p.priceLabel} <small style="font:500 .82rem 'DM Sans';color:var(--muted)">USD</small></div><p>${p.description}</p><div class="detail-spec-grid">${p.specs.map((s,i)=>`<div class="spec-box"><small>${['Configuration','Performance','Model year'][i]}</small><strong>${s}</strong></div>`).join('')}</div><p class="muted" style="font-size:.82rem">Shipping is quoted separately based on destination. Our team will confirm the final rate before dispatch.</p><button class="btn" id="addToCart">Add to cart · ${p.priceLabel}</button><a class="btn btn-light" href="shipping.html">Estimate shipping</a></div>`;document.getElementById('addToCart').addEventListener('click',()=>{const c=cart(),existing=c.find(x=>x.id===p.id);if(existing)existing.qty++;else c.push({id:p.id,qty:1});saveCart(c);const b=document.getElementById('addToCart');b.textContent='Added to your cart ✓';setTimeout(()=>b.textContent=`Add to cart · ${p.priceLabel}`,1800)})}
 const checkout=document.getElementById('checkoutItems');if(checkout){const c=cart();const selected=c.map(x=>({...products.find(p=>p.id===x.id),qty:x.qty})).filter(x=>x.id);if(!selected.length){checkout.innerHTML='<div class="empty-state"><h3>Your cart is ready for a journey.</h3><p>Browse our vehicles and add one to get started.</p><a class="btn" href="vehicles.html">Explore vehicles</a></div>';document.getElementById('checkoutSummary').style.display='none'}else{checkout.innerHTML=selected.map(p=>`<div class="checkout-item"><img src="${p.image}" alt=""><div style="flex:1"><h3>${p.name}</h3><p>${p.category} · Qty ${p.qty}</p><strong>${p.priceLabel}</strong></div><button class="btn btn-light btn-sm remove-item" data-id="${p.id}">Remove</button></div>`).join('');const sum=selected.reduce((n,p)=>n+p.price*p.qty,0);document.getElementById('subtotal').textContent='$'+sum.toLocaleString('en-US');document.getElementById('total').textContent='$'+sum.toLocaleString('en-US');checkout.querySelectorAll('.remove-item').forEach(b=>b.addEventListener('click',()=>{saveCart(cart().filter(x=>x.id!==b.dataset.id));location.reload()}))}}
 document.getElementById('checkoutForm')?.addEventListener('submit',e=>{e.preventDefault();if(!cart().length)return;const ref='GL-'+Math.random().toString(36).slice(2,8).toUpperCase();localStorage.setItem('gl-last-order',ref);saveCart([]);document.getElementById('checkoutMessage').innerHTML=`Your order request is confirmed. Reference <strong>${ref}</strong>. Our vehicle specialist will contact you to confirm payment and delivery details.`;document.getElementById('checkoutMessage').style.display='block';document.getElementById('checkoutForm').reset()});
 document.getElementById('trackForm')?.addEventListener('submit',e=>{e.preventDefault();const ref=document.getElementById('trackingNumber').value.trim().toUpperCase();const result=document.getElementById('trackingResult');result.style.display='block';result.innerHTML=`<h3>Shipment ${ref}</h3><p class="muted">Estimated arrival: 12–18 business days · Status: In transit to export terminal</p><div class="status-steps"><div class="status-step done">Order confirmed</div><div class="status-step done">Vehicle prepared</div><div class="status-step done">In transit</div><div class="status-step">Delivered</div></div><p class="muted" style="font-size:.82rem">Demo tracking view. Your dedicated shipping coordinator will share live carrier updates after dispatch.</p>`});
 document.getElementById('shippingForm')?.addEventListener('submit',e=>{e.preventDefault();const type=document.getElementById('shipType').value,region=document.getElementById('destination').value;const base=type==='aircraft'?6800:type==='cars'?2400:950;const multiplier=region==='Europe'?1:region==='Asia Pacific'?1.35:region==='Africa'?1.15:1.2;const rate=Math.round(base*multiplier/50)*50;const out=document.getElementById('shippingQuote');out.innerHTML=`<strong>Estimated shipping: $${rate.toLocaleString('en-US')} USD</strong><br><span>Typical transit time: ${region==='Europe'?'10–16':region==='Asia Pacific'?'18–28':'14–22'} business days. Final quote confirmed after vehicle inspection.</span>`;out.style.display='block'});
 document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();const n=document.getElementById('contactName').value;const out=document.getElementById('contactMessage');out.textContent=`Thanks, ${n}. Your message is with our mobility team. We’ll be in touch shortly.`;out.style.display='block';e.target.reset()});
});
